# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта +
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Морковь",
  "description": "Овощи"
}

###

# получение продуктов +
GET {{baseUrl}}/products/?limit=2&offset=1
Content-Type: application/json

###

# обновление продукта +
PATCH {{baseUrl}}/products/5/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта +
DELETE {{baseUrl}}/products/4/
Content-Type: application/json

###

# поиск продуктов по названию и описанию +
GET {{baseUrl}}/products/?search=свекла
Content-Type: application/json

###

# получение складов +
GET {{baseUrl}}/stocks/?limit=5&offset=5
Content-Type: application/json
###

# создание склада +
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Адрес6",
  "positions": [
    {
      "product": 4,
      "quantity": 580,
      "price": 145.50
    },
    {
      "product": 7,
      "quantity": 1000,
      "price": 190
    }
  ]
}

###

# обновляем записи на складе +
PATCH {{baseUrl}}/stocks/14/
Content-Type: application/json

{
  "positions": [{
      "product": 8,
      "quantity": 100,
      "price": 150
    },
    {
      "product": 7,
      "quantity": 230,
      "price": 145
    }]
}

###

# поиск складов, где есть определенный продукт +
GET {{baseUrl}}/stocks/?products=8
Content-Type: application/json

###

# удаление склада +
DELETE {{baseUrl}}/stocks/13
Content-Type: application/json
